name: Checks and Build

on: [push, pull_request]

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  code-checks-scala:
    name: Code Checks for Scala
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Set up JDK 1.8
        uses: actions/setup-java@b6e674f4b717d7b0ae3baee0fbe79f498905dfde # v1.4.4
        with:
          java-version: 1.8
      - name: Check Scala code
        run: |
          cd ${{github.workspace}}/mllib-dal
          ${{github.workspace}}/dev/code-checks/lint-scala.sh

  code-checks-java:
    name: Code Checks for Java
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Set up JDK 1.8
        uses: actions/setup-java@b6e674f4b717d7b0ae3baee0fbe79f498905dfde # v1.4.4
        with:
          java-version: 1.8
      - name: Check Java code
        run: |
          cd ${{github.workspace}}/mllib-dal
          ${{github.workspace}}/dev/code-checks/lint-java.sh

  code-checks-cpp:
    name: Code Checks for C++
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format
      - name: Check C++ code
        run: |
          cd ${{github.workspace}}/mllib-dal/src/main/native
          ${{github.workspace}}/dev/code-checks/lint-cpp.sh

  code-build:
    name: Build Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Set up JDK 1.8
        uses: actions/setup-java@b6e674f4b717d7b0ae3baee0fbe79f498905dfde # v1.4.4
        with:
          java-version: 1.8
      - name: Restore cached dependencies
        uses: actions/cache@f4b3439a656ba812b8cb417d2d49f9c810103092 # v3.4.0
        with:
          path: |
            #/var/cache/apt/archives/*.deb
            ~/.m2/repository
            /opt/intel/oneapi
            ~/opt
          key: ${{ runner.os }}_spark-3.3.3_hadoop-3.2.0_oneapi-2025.2
          restore-keys: |
            ${{ runner.os }}-
      - name: Build Test for CPU and GPU
        run: |
          ${{github.workspace}}/dev/ci/ci-build-test.sh
