name: OAP MLlib Checks and Build

on: [push, pull_request]

jobs:
  code-checks-scala:
    name: Code Checks for Scala
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Check Scala code
        run: |
          cd ${{github.workspace}}/mllib-dal
          ${{github.workspace}}/dev/code-checks/lint-scala.sh

  code-checks-java:
    name: Code Checks for Java
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Check Java code
        run: |
          cd ${{github.workspace}}/mllib-dal
          ${{github.workspace}}/dev/code-checks/lint-java.sh

  code-checks-cpp:
    name: Code Checks for C++
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format-10
      - name: Check C++ code
        run: |
          cd ${{github.workspace}}/mllib-dal/src/main/native
          ${{github.workspace}}/dev/code-checks/lint-cpp.sh

  code-build:
    name: Code Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Restore cached dependencies
        uses: actions/cache/@v3
        with:
          path: |
            /var/cache/apt/archives/*.deb
            ~/.m2/repository
            /opt/intel/oneapi
            ~/opt
          key: ${{ runner.os }}_spark-3.2.0_hadoop-3.2.0_oneapi-2023.0.0
          restore-keys: |
            ${{ runner.os }}-
      - name: Build Test for CPU and GPU
        run: |
          ${{github.workspace}}/dev/ci/ci-build-test.sh
