name: OAP MLlib CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8      
      - name: Restore cached dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/downloads
            /opt/intel/inteloneapi
            /opt/intel/oneapi
          key: ${{ runner.os }}-${{ hashFiles('**/pom.xml', '{{github.workspace}}/dev/install-build-deps-ubuntu.sh') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Set up dependencies
        run: |
          [ -d ~/downloads ] || mkdir ~/downloads
          cd ~/downloads
          [ -f spark-3.0.0-bin-hadoop2.7.tgz ] || wget --no-verbose http://archive.apache.org/dist/spark/spark-3.0.0/spark-3.0.0-bin-hadoop2.7.tgz
          [ -d spark-3.0.0-bin-hadoop2.7 ] || cd ~ && tar -zxf downloads/spark-3.0.0-bin-hadoop2.7.tgz
          export SPARK_HOME=~/spark-3.0.0-bin-hadoop2.7
          ${{github.workspace}}/dev/install-build-deps-ubuntu.sh
      - name: Build and Test
        run: |
          cd ${{github.workspace}}/mllib-dal      
          export ONEAPI_ROOT=/opt/intel/oneapi
          source /opt/intel/oneapi/dal/latest/env/vars.sh
          source /opt/intel/oneapi/tbb/latest/env/vars.sh
          source /opt/intel/oneapi/ccl/latest/env/vars.sh          
          ./build.sh
          ./test.sh
          ./test-cluster.sh
